hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 60
    cpus_per_task: null
    gpus_per_node: null
    tasks_per_node: 1
    mem_gb: null
    nodes: 1
    name: ${hydra.job.name}
    stderr_to_stdout: false
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    partition: null
    qos: null
    comment: null
    constraint: null
    exclude: null
    gres: null
    cpus_per_gpu: null
    gpus_per_task: null
    mem_per_gpu: null
    mem_per_cpu: null
    account: null
    signal_delay_s: 120
    max_num_timeout: 0
    additional_parameters: {}
    array_parallelism: 256
    setup: null
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra: []
    task:
    - ndim=4
    - horizon=16
    - method=fm_egfn
    - replay_sample_size=16
    - super_mutation_prob=0.05,0.25,0.5
  job:
    name: run_hydra
    override_dirname: horizon=16,method=fm_egfn,ndim=4,replay_sample_size=16,super_mutation_prob=0.05,0.25,0.5
    id: ???
    num: ???
    config_name: main
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.1.0
    cwd: /Users/zarifikram/Documents/Repos/E-GFN/grid
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /Users/zarifikram/Documents/Repos/E-GFN/grid/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: submitit_slurm
      hydra/output: default
  verbose: false
user: ${oc.env:USER}
wandb: 0
save_path: output/flow_insp_0.pkl.gz
device: cpu
seed: 0
progress: 1
method: fm_egfn
lr: 0.0001
opt: adam
adam_beta1: 0.9
adam_beta2: 0.999
momentum: 0.9
mbsize: 16
train_to_sample_ratio: 1
n_hid: 256
n_layers: 2
n_train_steps: 1000
num_empirical_loss: 200000
func: corner
R0: 0.001
R1: 0.5
R2: 2.0
horizon: 16
ndim: 4
bufsize: 16
bootstrap_tau: 0.0
replay_strategy: top_k
replay_sample_size: 16
replay_buf_size: 4000
exp_weight: 0.0
temp: 1.0
rand_pb: 0
tlr: 0.001
zlr: 0.1
leaf_coef: 1.0
ts: false
'N': 8
quantile_dim: 256
beta: neutral
eta: 0.0
indist: false
outdist: false
population_size: 10
num_eval_episodes: 4
num_elites: 2
tournament_size: 4
mutation: true
crossover_prob: 0.1
mutation_prob: 0.9
mutation_frac: 0.1
mutation_strength: 0.1
super_mutation_strength: 10
super_mutation_prob: 0.05
reset_prob: 0.1
weight_limit: 100000
ppo_num_epochs: 32
ppo_epoch_size: 16
ppo_clip: 0.2
ppo_entropy_coef: 0.1
clip_grad_norm: 0.0
sac_alpha: -1.0766
